### PR TITLE
pdc_events.html

### PR DESCRIPTION
**Pull request by perezdotcom**
Steve's edit to add the events page.
Steve's to main begin at:
/* Styles for PDC_EVENTS SECTION */

### CODE REVIEW

**Comment by perezdotcom** [comment]
welp, pushed the new events page from desktop and the images but not seeing it here. Hope you all can help with the button pushing tomorrow .

**Comment by gulincourses** [comment]
steve, only push this to your branch, not the main yet

**Comment by perezdotcom** [comment]
All my im=

**Comment by gulincourses** [comment]
please commit to your own branch only at this point

**Pull request closed without merging**
