### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by gulincourses**
remove nav for footer

### CODE REVIEW

**Comment by SnehaPawar20** [comment]
good

**Comment by perezdotcom** [comment]
Approved1

**Comment by gulincourses** [comment]
comment

**Review by SnehaPawar20 — APPROVED** [review]
removed something

**Comment by gulincourses** [comment]
nav update

**Comment by perezdotcom** [comment]
INDEX.HTML as of this writing (9:12 Pacific, 5/2/2024) contains two addresses:
LINES 104-111
   <p>7304 Parkway Drive S, Hanover, MD 21076</p>
        </article>
        <article>
          <header>
            <i class="fa-solid fa-location-dot"></i>
            <h3>Contact us</h3>
          </header>
          <p>7304 Parkway Drive S, Hanover, MD 21076</p>

**Pull request merged**
